import { AnimationConfig, AnimateEntry, AnimateExit } from '@inithium/types';

export const DEFAULT_ANIMATION_CONFIG: Required<AnimationConfig> = {
  entry: 'fadeIn',
  exit: 'fadeOut',
  duration: 200,
  delay: 0,
  timing: 'ease-out',
};

export const ENTRY_CLASS_MAP: Record<AnimateEntry, string> = {
  backInDown: 'animate-backInDown',
  backInLeft: 'animate-backInLeft',
  backInRight: 'animate-backInRight',
  backInUp: 'animate-backInUp',
  bounceIn: 'animate-bounceIn',
  bounceInDown: 'animate-bounceInDown',
  bounceInLeft: 'animate-bounceInLeft',
  bounceInRight: 'animate-bounceInRight',
  bounceInUp: 'animate-bounceInUp',
  fadeIn: 'animate-fadeIn opacity-100',
  fadeInDown: 'animate-fadeInDown',
  fadeInLeft: 'animate-fadeInLeft',
  fadeInRight: 'animate-fadeInRight',
  fadeInUp: 'animate-fadeInUp',
  flipInX: 'animate-flipInX',
  flipInY: 'animate-flipInY',
  lightSpeedInLeft: 'animate-lightSpeedInLeft',
  lightSpeedInRight: 'animate-lightSpeedInRight',
  rotateIn: 'animate-rotateIn',
  rotateInDownLeft: 'animate-rotateInDownLeft',
  rotateInDownRight: 'animate-rotateInDownRight',
  rotateInUpLeft: 'animate-rotateInUpLeft',
  rotateInUpRight: 'animate-rotateInUpRight',
  zoomIn: 'animate-zoomIn',
  zoomInDown: 'animate-zoomInDown',
  zoomInLeft: 'animate-zoomInLeft',
  zoomInRight: 'animate-zoomInRight',
  zoomInUp: 'animate-zoomInUp',
  slideInDown: 'animate-slideInDown',
  slideInLeft: 'animate-slideInLeft',
  slideInRight: 'animate-slideInRight',
  slideInUp: 'animate-slideInUp',
};

export const EXIT_CLASS_MAP: Record<AnimateExit, string> = {
  backOutDown: 'animate-backOutDown',
  backOutLeft: 'animate-backOutLeft',
  backOutRight: 'animate-backOutRight',
  backOutUp: 'animate-backOutUp',
  bounceOut: 'animate-bounceOut',
  bounceOutDown: 'animate-bounceOutDown',
  bounceOutLeft: 'animate-bounceOutLeft',
  bounceOutRight: 'animate-bounceOutRight',
  bounceOutUp: 'animate-bounceOutUp',
  fadeOut: 'animate-fadeOut opacity-0',
  fadeOutDown: 'animate-fadeOutDown',
  fadeOutLeft: 'animate-fadeOutLeft',
  fadeOutRight: 'animate-fadeOutRight',
  fadeOutUp: 'animate-fadeOutUp',
  fadeOutTopLeft: 'animate-fadeOutTopLeft',
  fadeOutTopRight: 'animate-fadeOutTopRight',
  fadeOutBottomLeft: 'animate-fadeOutBottomLeft',
  fadeOutBottomRight: 'animate-fadeOutBottomRight',
  flipOutX: 'animate-flipOutX',
  flipOutY: 'animate-flipOutY',
  lightSpeedOutLeft: 'animate-lightSpeedOutLeft',
  lightSpeedOutRight: 'animate-lightSpeedOutRight',
  rotateOut: 'animate-rotateOut',
  rotateOutDownLeft: 'animate-rotateOutDownLeft',
  rotateOutDownRight: 'animate-rotateOutDownRight',
  rotateOutUpLeft: 'animate-rotateOutUpLeft',
  rotateOutUpRight: 'animate-rotateOutUpRight',
  zoomOut: 'animate-zoomOut',
  zoomOutDown: 'animate-zoomOutDown',
  zoomOutLeft: 'animate-zoomOutLeft',
  zoomOutRight: 'animate-zoomOutRight',
  zoomOutUp: 'animate-zoomOutUp',
  slideOutDown: 'animate-slideOutDown',
  slideOutLeft: 'animate-slideOutLeft',
  slideOutRight: 'animate-slideOutRight',
  slideOutUp: 'animate-slideOutUp',
  hinge: 'animate-hinge',
  rollOut: 'animate-rollOut',
};